/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.zealep.vista;

import com.zealep.modelo.Pago;
import com.zealep.modelo.Tratamiento;
import com.zealep.negocio.PagoDAO;
import com.zealep.negocio.TratamientoDAO;
import com.zealep.util.FichaPagoDTO;
import com.zealep.util.PagosCuotaDTO;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import javax.swing.JDialog;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author user
 */
public class DialogFichaPagos extends javax.swing.JDialog {

    public static int IDTRATAMIENTO;
    PagoDAO pagoDAO = new PagoDAO();
    TratamientoDAO tratamientoDAO = new TratamientoDAO();
    public DialogFichaPagos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        mostrarFicha();
    }
    
    public void mostrarFicha()
    {   Tratamiento tratamiento = new Tratamiento();
        tratamiento = tratamientoDAO.listarTratamientoPorId(IDTRATAMIENTO);
        List<Pago> pagos = new ArrayList<>();
        pagos = pagoDAO.listarPagosDeCuotasPorTratamiento(IDTRATAMIENTO);
        DefaultTableModel modelo = new DefaultTableModel();
        String[] titulos = {"Fecha Pagar","Fecha realizo pago","N° Cuota","Estado"};
        modelo.setColumnIdentifiers(titulos);
        Object obj[] = new Object[modelo.getColumnCount()];
        
        SimpleDateFormat sd = new SimpleDateFormat("dd 'de' MMMM 'de' yyyy", new Locale("ES"));
        Date fechaInicioPago = tratamiento.getFechaInicioPago();
        int cuotas = tratamiento.getMesesTratamiento();
        
        List<String> fechasPagar = new ArrayList<>();
        List<Integer> nroCuotas = new ArrayList<>();
        List<String> fechaPagos = new ArrayList<>();
        List<String> estados = new ArrayList<>();
        
        
        //obtencion de cuotas
        for(int i=1;i<=cuotas;i++)
        {
            nroCuotas.add(i);
        }
     

        //ALGORITMO CONSTRUCCION DE PAGOS EN CUOTAS
        List<PagosCuotaDTO> fichas = new ArrayList<>();
        
        for(int i=0;i<nroCuotas.size();i++)
        {   PagosCuotaDTO f = new PagosCuotaDTO();
        
        if(i<pagos.size())
        {
        
          if(pagos.get(i).getNroCuota()==nroCuotas.get(i))
            {
               f.setFechaPago(pagos.get(i).getFechaPago());
               f.setNroCuota(nroCuotas.get(i));
               f.setEstado("CANCELADO");
            }
          
          else
          {   
               f.setFechaPago(null);
               f.setNroCuota(nroCuotas.get(i));
               f.setEstado("A DEUDA");
               
          }
             
        }
        
        else
        {
              f.setFechaPago(null);
              f.setNroCuota(nroCuotas.get(i));
              f.setEstado("A DEUDA");
        }
        
          fichas.add(f);

        }
        
      //
        
        fechasPagar.add(sd.format(fechaInicioPago));
        
        //obtencion de suma de meses
        for(int i=1;i<cuotas;i++)
        {
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(fechaInicioPago);
        calendar.add(Calendar.MONTH,i);
        Date fecha = calendar.getTime();
        String fechaPagar = sd.format(fecha);
        fechasPagar.add(fechaPagar);
        }
        
        
        //llenado de tabla fechas pagar
      for(int i=0;i <fechasPagar.size();i++)
      {
          
          obj[0]= fechasPagar.get(i);
          obj[1]= fichas.get(i).getFechaPago();
          obj[2]= fichas.get(i).getNroCuota();
          obj[3]= fichas.get(i).getEstado();
          modelo.addRow(obj);
      }
        
        tableFichaPagos.setModel(modelo);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableFichaPagos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnContrato = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableFichaPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableFichaPagos);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(40, 96, 134));
        jLabel1.setText("Ficha de Pagos");

        btnContrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/printer.png"))); // NOI18N
        btnContrato.setText("Imprimir");
        btnContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContratoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnContrato)
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContratoActionPerformed
        
        DefaultTableModel df = (DefaultTableModel) tableFichaPagos.getModel();
         SimpleDateFormat sd = new SimpleDateFormat("dd 'de' MMMM 'de' yyyy", new Locale("ES"));
         List<FichaPagoDTO> fichaPagoDTOs = new ArrayList<>();
         
         Tratamiento t = tratamientoDAO.listarTratamientoPorId(IDTRATAMIENTO);
         
         String apellidos;
         String nombres;
         String nroHistoria;
         String dni;
         
         apellidos = t.getPaciente().getApellidos();
         nombres = t.getPaciente().getNombres();
         nroHistoria = t.getPaciente().getNroHistoria();
         dni = t.getPaciente().getDni();
         
         for(int i=0;i<df.getRowCount();i++)
         {
             FichaPagoDTO fichaPagoDTO = new FichaPagoDTO();
             fichaPagoDTO.setFechaPagar(df.getValueAt(i,0).toString());
             fichaPagoDTO.setFechaPago(df.getValueAt(i,1).toString());
             fichaPagoDTO.setNroCuota(df.getValueAt(i,2).toString());
             fichaPagoDTO.setEstado(df.getValueAt(i,3).toString());
             
              fichaPagoDTOs.add(fichaPagoDTO);
         }
     
        Map p = new HashMap();

        String logo = "/imagenes/diamante.png";
        p.put("logo", this.getClass().getResourceAsStream(logo));
        p.put("apellidos", apellidos);
        p.put("nombres",nombres);
        p.put("nroHistoria",nroHistoria);
        p.put("dni",dni);
        
        JasperReport report;
        JasperPrint print;

        try {

            URL url = this.getClass().getResource("/reportes/RptFichaPagos.jasper");
            report = (JasperReport) JRLoader.loadObject(url);
            //report = JasperCompileManager.compileReport(new File("").getAbsolutePath()+"\\src\\reportes\\RptContratoTratamiento.jrxml");
            print = JasperFillManager.fillReport(report, p, new JRBeanCollectionDataSource(fichaPagoDTOs));
            JasperViewer view = new JasperViewer(print, false);
            //jasperviewer como dialog
            JDialog dialog = new JDialog(this);//the owner
            dialog.setContentPane(view.getContentPane());
            dialog.setSize(view.getSize());
            dialog.setTitle("Contrato de Tratamiento");
            dialog.setVisible(true);

        } catch (JRException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnContratoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogFichaPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogFichaPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogFichaPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogFichaPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogFichaPagos dialog = new DialogFichaPagos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContrato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableFichaPagos;
    // End of variables declaration//GEN-END:variables
}
