/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.zealep.vista;

import com.zealep.modelo.Tratamiento;
import com.zealep.negocio.TratamientoDAO;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author user
 */
public class FrmConsultaTratamiento extends javax.swing.JInternalFrame {

   TratamientoDAO tratamientoDAO = new TratamientoDAO();
    Tratamiento tratamiento = new Tratamiento();
    TableRowSorter trsFiltro;
    public FrmConsultaTratamiento() {
        initComponents();
        mostrar();
    }
    
    public void mostrar() {

        List<Tratamiento> tratamientos = new ArrayList<>();
        tratamientos = tratamientoDAO.listarTratamientos();
        DefaultTableModel modelo = new DefaultTableModel();
        String[] titulos = {"Id", "Apellidos", "Nombres", "Dni", "Nro Historia", "A.Doctor", "N.Doctor","F.Registro","N° Meses", "Pago Mensual", "Costo Total", "Dia Pago", "Comentarios", "Estado"};
        modelo.setColumnIdentifiers(titulos);
        Object obj[] = new Object[modelo.getColumnCount()];

        for (int i = 0; i < tratamientos.size(); i++) {
            obj[0] = tratamientos.get(i).getIdTratamiento();
            obj[1] = tratamientos.get(i).getPaciente().getApellidos();
            obj[2] = tratamientos.get(i).getPaciente().getNombres();
            obj[3] = tratamientos.get(i).getPaciente().getDni();
            obj[4] = tratamientos.get(i).getPaciente().getNroHistoria();
            obj[5] = tratamientos.get(i).getDoctor().getApellidos();
            obj[6] = tratamientos.get(i).getDoctor().getNombres();
            obj[7] = tratamientos.get(i).getFechaRegistro();
            obj[8] = tratamientos.get(i).getMesesTratamiento();
            obj[9] = tratamientos.get(i).getPagoMensual();
            obj[10] = tratamientos.get(i).getMontoTotal();
            obj[11] = tratamientos.get(i).getDiaPagar();
            obj[12] = tratamientos.get(i).getComentarios();
            obj[13] = tratamientos.get(i).getEstado();

            modelo.addRow(obj);

        }

        tableTratamiento.setModel(modelo);
        // lblCantidadRegistros.setText("La cantidad de pacientes es: " + String.valueOf(tratamientoDAO.cantidadRegistros));

    }
    void busquedaFiltro() {

        int opcionBuscar = 0;

        if (rbApellidos.isSelected()) {
            opcionBuscar = 1;
        } else if (rbNombres.isSelected()) {
            opcionBuscar = 2;
        } else if (rbDni.isSelected()) {
            opcionBuscar = 3;
        }
        else if (rbFechaRegistro.isSelected()) {
            opcionBuscar = 7;
        }

        trsFiltro.setRowFilter(RowFilter.regexFilter("(?i)" + txtBuscar.getText(), opcionBuscar));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItemVerInfo = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        rbApellidos = new javax.swing.JRadioButton();
        rbNombres = new javax.swing.JRadioButton();
        rbDni = new javax.swing.JRadioButton();
        txtBuscar = new javax.swing.JTextField();
        rbFechaRegistro = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTratamiento = new javax.swing.JTable();

        jMenuItemVerInfo.setText("Ver Detalle");
        jMenuItemVerInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerInfoActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItemVerInfo);

        setClosable(true);
        setTitle("Busqueda General de los Tratamientos de los Pacientes");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Criterios de busqueda"));

        buttonGroup1.add(rbApellidos);
        rbApellidos.setText("Apellidos");

        buttonGroup1.add(rbNombres);
        rbNombres.setText("Nombres");

        buttonGroup1.add(rbDni);
        rbDni.setText("Dni");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });

        buttonGroup1.add(rbFechaRegistro);
        rbFechaRegistro.setText("Fecha Contrato");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rbApellidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbNombres)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbDni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbFechaRegistro)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbApellidos)
                    .addComponent(rbNombres)
                    .addComponent(rbDni)
                    .addComponent(rbFechaRegistro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableTratamiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableTratamiento.setComponentPopupMenu(jPopupMenu1);
        tableTratamiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTratamientoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableTratamiento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1459, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        txtBuscar.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(final KeyEvent e) {
                String cadena = (txtBuscar.getText());
                txtBuscar.setText(cadena);
                repaint();
                busquedaFiltro();
            }
        });
        trsFiltro = new TableRowSorter(tableTratamiento.getModel());
        tableTratamiento.setRowSorter(trsFiltro);
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void tableTratamientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTratamientoMouseClicked
        DefaultTableModel defaultTableModel = (DefaultTableModel) tableTratamiento.getModel();
       int fila = tableTratamiento.convertRowIndexToModel(tableTratamiento.getSelectedRow());
       int idTratamiento = Integer.parseInt(defaultTableModel.getValueAt(fila,0).toString());
       DialogInfoTratamiento.IDTRATAMIENTO = idTratamiento;
       DialogInfoTratamiento dialogInfoTratamiento = new DialogInfoTratamiento(null, closable);
       dialogInfoTratamiento.setLocationRelativeTo(null);
       dialogInfoTratamiento.show();
    }//GEN-LAST:event_tableTratamientoMouseClicked

    private void jMenuItemVerInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerInfoActionPerformed
        
       DefaultTableModel defaultTableModel = (DefaultTableModel) tableTratamiento.getModel();
       int fila = tableTratamiento.convertRowIndexToModel(tableTratamiento.getSelectedRow());
       int idTratamiento = Integer.parseInt(defaultTableModel.getValueAt(fila,0).toString());
       DialogInfoTratamiento.IDTRATAMIENTO = idTratamiento;
       DialogInfoTratamiento dialogInfoTratamiento = new DialogInfoTratamiento(null, closable);
       dialogInfoTratamiento.setLocationRelativeTo(null);
       dialogInfoTratamiento.show();
    }//GEN-LAST:event_jMenuItemVerInfoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuItem jMenuItemVerInfo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbApellidos;
    private javax.swing.JRadioButton rbDni;
    private javax.swing.JRadioButton rbFechaRegistro;
    private javax.swing.JRadioButton rbNombres;
    private javax.swing.JTable tableTratamiento;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
