/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.zealep.vista;

import com.zealep.modelo.Paciente;
import com.zealep.negocio.PacienteDAO;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Proysym01
 */
public class FrmCumpleaños extends javax.swing.JInternalFrame {
    
    
    PacienteDAO pacienteDAO = new PacienteDAO();
    public FrmCumpleaños() {
        initComponents();
         mostrar();
    }
    
    
    public void mostrar()
    {   
        List<Paciente> pacientes = new ArrayList<>();
        pacientes = pacienteDAO.listarCumpleañosPacientes();
        
        DefaultTableModel modelo = new DefaultTableModel();
        String[] columnNames = {"ID","Apellidos","Nombres","Telefono","Celular","Email"};
        modelo.setColumnIdentifiers(columnNames);
        Object obj[]= new Object[modelo.getColumnCount()];
        
        for(int i=0;i<pacientes.size();i++)
        {   obj[0] = pacientes.get(i).getIdPaciente();
            obj[1] = pacientes.get(i).getApellidos();
            obj[2] = pacientes.get(i).getNombres();
            obj[3] = pacientes.get(i).getTelefono();
            obj[4] = pacientes.get(i).getCelular();
            obj[5] = pacientes.get(i).getEmail();
            
            modelo.addRow(obj);
                       
        }
        
        tableCumpleaños.setModel(modelo);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableCumpleaños = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblFoto = new javax.swing.JLabel();

        setClosable(true);

        tableCumpleaños = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;
            }
        };
        tableCumpleaños.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableCumpleaños.setFocusable(false);
        tableCumpleaños.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCumpleañosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCumpleaños);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(40, 96, 134));
        jLabel1.setText("Cumpleños del dia de hoy");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/globos.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/globos.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 965, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableCumpleañosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCumpleañosMouseClicked
         int fila;
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        fila = tableCumpleaños.getSelectedRow();
        defaultTableModel = (DefaultTableModel)tableCumpleaños.getModel();

        //mostrar foto
        String ruta = pacienteDAO.obtenerRutaFoto(Integer.parseInt(defaultTableModel.getValueAt(fila, 0).toString()));
        ImageIcon img = new ImageIcon(ruta);
        Image imagen = img.getImage();
        BufferedImage resizedImg = new BufferedImage(lblFoto.getWidth(),lblFoto.getHeight(), BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2 = resizedImg.createGraphics();

        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.drawImage(imagen, 0, 0, lblFoto.getWidth(),lblFoto.getHeight(), null);
        g2.dispose();
        ImageIcon imagenRediseñada = new ImageIcon(resizedImg);     
        lblFoto.setIcon(imagenRediseñada);
    }//GEN-LAST:event_tableCumpleañosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JTable tableCumpleaños;
    // End of variables declaration//GEN-END:variables
}
