/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.zealep.vista;

import com.zealep.modelo.Pago;
import com.zealep.negocio.PagoDAO;
import com.zealep.util.PagosPacienteDTO;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author user
 */
public class FrmHistorialPago extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmHistorialPago
     */
    public FrmHistorialPago() {
        initComponents();
        txtIdTratamiento.setVisible(false);
      
    }

    public void limpiar() {
        
        txtTotalPagado.setText("");
        txtSaldoPendiente.setText("");
        txtApellidosPa.setText("");
        txtCostoTotal.setText("");
        txtDiaPago.setText("");
        txtIdTratamiento.setText("");
        txtMeses.setText("");
        txtNombresPa.setText("");
        txtNroHistoria.setText("");
        txtPagoMensual.setText("");
        txtFechaRegistro.setText("");
        limpiarTabla(tablePagosTratamiento);
    }
    
       public void limpiarTabla(JTable tabla) {
        DefaultTableModel tb = (DefaultTableModel) tabla.getModel();
        int a = tabla.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            tb.removeRow(tb.getRowCount() - 1);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtApellidosPa = new javax.swing.JTextField();
        txtNombresPa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNroHistoria = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCostoTotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtMeses = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDiaPago = new javax.swing.JTextField();
        btnSeleccionar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtPagoMensual = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtFechaRegistro = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePagosTratamiento = new javax.swing.JTable();
        cboMes = new com.toedter.calendar.JMonthChooser();
        spnAnho = new com.toedter.calendar.JYearChooser();
        btnBuscarPorFecha = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        btnVerPagos = new javax.swing.JButton();
        txtIdTratamiento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtTotalPagado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSaldoPendiente = new javax.swing.JTextField();
        btnDetalleTratamiento = new javax.swing.JButton();
        btnVerFichaPago = new javax.swing.JButton();
        btnVerControles = new javax.swing.JButton();

        setClosable(true);
        setTitle("Historial de Pagos y Controles por Tratamiento del Paciente");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Buscar Tratamiento del Paciente"));

        jLabel3.setText("Apellidos :");

        jLabel4.setText("Nombres :");

        txtApellidosPa.setEnabled(false);

        txtNombresPa.setEnabled(false);

        jLabel6.setText("Nro Historia");

        txtNroHistoria.setEnabled(false);

        jLabel7.setText("Costo Total Tratamiento :");

        txtCostoTotal.setEnabled(false);

        jLabel8.setText("N° Cuotas :");

        txtMeses.setEnabled(false);

        jLabel9.setText("Dia de Pago :");

        txtDiaPago.setEnabled(false);

        btnSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Buscar_32.png"))); // NOI18N
        btnSeleccionar.setText("Buscar Paciente");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        jLabel5.setText("Pago Mensual :");

        txtPagoMensual.setEditable(false);
        txtPagoMensual.setEnabled(false);

        jLabel11.setText("Fecha Inicio Pago :");

        txtFechaRegistro.setEditable(false);
        txtFechaRegistro.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtApellidosPa, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(txtNroHistoria)
                            .addComponent(txtCostoTotal)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPagoMensual, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombresPa)
                    .addComponent(txtMeses)
                    .addComponent(txtDiaPago, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(txtFechaRegistro))
                .addGap(29, 29, 29)
                .addComponent(btnSeleccionar)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(txtApellidosPa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombresPa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtNroHistoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtCostoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtDiaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtPagoMensual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txtFechaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnSeleccionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Pagos del Tratamiento"));

        tablePagosTratamiento = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;
            }
        };
        tablePagosTratamiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablePagosTratamiento);

        btnBuscarPorFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Buscar_p.png"))); // NOI18N
        btnBuscarPorFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPorFechaActionPerformed(evt);
            }
        });

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Refresh.png"))); // NOI18N
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/report.png"))); // NOI18N
        btnReporte.setText("Reporte Pagos");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cboMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnAnho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarPorFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset)
                        .addGap(18, 18, 18)
                        .addComponent(btnReporte))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 993, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cboMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spnAnho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscarPorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnVerPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/importe.png"))); // NOI18N
        btnVerPagos.setText("VER PAGOS REALIZADOS");
        btnVerPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPagosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(40, 96, 134));
        jLabel1.setText("TOTAL PAGADO ");

        txtTotalPagado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTotalPagado.setForeground(new java.awt.Color(40, 96, 134));
        txtTotalPagado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalPagado.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(40, 96, 134));
        jLabel2.setText("SALDO PENDIENTE ");

        txtSaldoPendiente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtSaldoPendiente.setForeground(new java.awt.Color(40, 96, 134));
        txtSaldoPendiente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSaldoPendiente.setEnabled(false);

        btnDetalleTratamiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Buscadetalle_p.png"))); // NOI18N
        btnDetalleTratamiento.setText("VER DETALLE TRATAMIENTO");
        btnDetalleTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalleTratamientoActionPerformed(evt);
            }
        });

        btnVerFichaPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ventasrealizadas.png"))); // NOI18N
        btnVerFichaPago.setText("VER FICHA CUOTAS");
        btnVerFichaPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerFichaPagoActionPerformed(evt);
            }
        });

        btnVerControles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ventasdetalladas.png"))); // NOI18N
        btnVerControles.setText("VER CONTROLES");
        btnVerControles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerControlesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnVerPagos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnDetalleTratamiento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnVerFichaPago)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnVerControles)))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(txtTotalPagado)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSaldoPendiente, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTotalPagado, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSaldoPendiente, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnVerFichaPago)
                                        .addComponent(btnVerControles))
                                    .addComponent(btnVerPagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDetalleTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        limpiar();
        DialogTratamientos dialogTratamientos = new DialogTratamientos(null, closable);
        DialogTratamientos.llamado = "historial";
        dialogTratamientos.show();
        

    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnVerPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPagosActionPerformed
      if(txtApellidosPa.getText().equals(""))
      {
          JOptionPane.showMessageDialog(this,"Debes de buscar un tratamiento del paciente","ADVERTENCIA",JOptionPane.WARNING_MESSAGE);
      }
      else{
        DefaultTableModel modelo = new DefaultTableModel();
        PagoDAO pagoDAO = new PagoDAO();
        List<Pago> pagos = new ArrayList<Pago>();
        int cantidadRegistros = 0;
        double totalPagado = 0;
        double saldo = 0;
        int cuotasFaltantes = 0;
        double costoTotal = Double.parseDouble(txtCostoTotal.getText());
        SimpleDateFormat formateador = new SimpleDateFormat("dd 'de' MMMM 'de' yyyy", new Locale("ES"));
        pagos = pagoDAO.listarPagosPorTratamiento(Integer.parseInt(txtIdTratamiento.getText()));
        String[] titulos = {"Nro Cuota","Fecha de Pago","Pago Ortodontico","Pago Adicional","Monto Total"};
        modelo.setColumnIdentifiers(titulos);
        Object obj[] = new Object[modelo.getColumnCount()];

        for (int i = 0; i < pagos.size(); i++) {
            obj[0] = pagos.get(i).getNroCuota();
            obj[1] = formateador.format(pagos.get(i).getFechaPago());
            obj[2] = pagos.get(i).getPagoOrtodontico();
            obj[3] = pagos.get(i).getPagoAdicional();
            obj[4] = pagos.get(i).getMonto();
      
            modelo.addRow(obj);
            cantidadRegistros++;
            totalPagado = totalPagado + pagos.get(i).getMonto();

        }

        saldo = costoTotal - totalPagado;
        tablePagosTratamiento.setModel(modelo);
        txtTotalPagado.setText(String.valueOf(totalPagado));
        txtSaldoPendiente.setText(String.valueOf(saldo));
      }
    }//GEN-LAST:event_btnVerPagosActionPerformed

    private void btnBuscarPorFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPorFechaActionPerformed
        if(txtApellidosPa.getText().equals(""))
      {
          JOptionPane.showMessageDialog(this,"Debes de buscar un tratamiento del paciente","ADVERTENCIA",JOptionPane.WARNING_MESSAGE);
      }
        
        else
        {
        
        DefaultTableModel modelo = new DefaultTableModel();
        PagoDAO pagoDAO = new PagoDAO();
        List<Pago> pagos = new ArrayList<Pago>();
        SimpleDateFormat formateador = new SimpleDateFormat("dd 'de' MMMM 'de' yyyy", new Locale("ES"));
        pagos = pagoDAO.listarPagosPorTratamientoYFecha(Integer.parseInt(txtIdTratamiento.getText()),spnAnho.getYear(),cboMes.getMonth()+1);
         String[] titulos = {"Nro Cuota","Fecha de Pago","Pago Ortodontico","Pago Adicional","Monto Total"};
        modelo.setColumnIdentifiers(titulos);
        Object obj[] = new Object[modelo.getColumnCount()];

        for (int i = 0; i < pagos.size(); i++) {
            obj[0] = pagos.get(i).getNroCuota();
            obj[1] = formateador.format(pagos.get(i).getFechaPago());
            obj[2] = pagos.get(i).getPagoOrtodontico();
            obj[3] = pagos.get(i).getPagoAdicional();
            obj[4] = pagos.get(i).getMonto();
            modelo.addRow(obj);
            
        }
         tablePagosTratamiento.setModel(modelo);
        }
    }//GEN-LAST:event_btnBuscarPorFechaActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
          if(txtApellidosPa.getText().equals(""))
      {
          JOptionPane.showMessageDialog(this,"Debes de buscar un tratamiento del paciente","ADVERTENCIA",JOptionPane.WARNING_MESSAGE);
      }
      else{
        DefaultTableModel modelo = new DefaultTableModel();
        PagoDAO pagoDAO = new PagoDAO();
        List<Pago> pagos = new ArrayList<Pago>();
        int cantidadRegistros = 0;
        double totalPagado = 0;
        double saldo = 0;
        int cuotasFaltantes = 0;
        double costoTotal = Double.parseDouble(txtCostoTotal.getText());
        SimpleDateFormat formateador = new SimpleDateFormat("dd 'de' MMMM 'de' yyyy", new Locale("ES"));
        pagos = pagoDAO.listarPagosPorTratamiento(Integer.parseInt(txtIdTratamiento.getText()));
        String[] titulos = {"Nro Cuota","Fecha de Pago","Pago Ortodontico","Pago Adicional","Monto Total"};
        modelo.setColumnIdentifiers(titulos);
        Object obj[] = new Object[modelo.getColumnCount()];

        for (int i = 0; i < pagos.size(); i++) {
            obj[0] = pagos.get(i).getNroCuota();
            obj[1] = formateador.format(pagos.get(i).getFechaPago());
            obj[2] = pagos.get(i).getPagoOrtodontico();
            obj[3] = pagos.get(i).getPagoAdicional();
            obj[4] = pagos.get(i).getMonto();
            modelo.addRow(obj);
            cantidadRegistros++;
            totalPagado = totalPagado + pagos.get(i).getMonto();

        }

        saldo = costoTotal - totalPagado;
        tablePagosTratamiento.setModel(modelo);
        txtTotalPagado.setText(String.valueOf(totalPagado));
        txtSaldoPendiente.setText(String.valueOf(saldo));
      }
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnDetalleTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalleTratamientoActionPerformed
              if(txtApellidosPa.getText().equals(""))
      {
          JOptionPane.showMessageDialog(this,"Debes de buscar un tratamiento del paciente","ADVERTENCIA",JOptionPane.WARNING_MESSAGE);
      }
              else
              {
       DialogInfoTratamiento.IDTRATAMIENTO = Integer.parseInt(txtIdTratamiento.getText());
       DialogInfoTratamiento dialogInfoTratamiento = new DialogInfoTratamiento(null, closable);
       dialogInfoTratamiento.setLocationRelativeTo(null);
       dialogInfoTratamiento.show();
              }
    }//GEN-LAST:event_btnDetalleTratamientoActionPerformed

    private void btnVerFichaPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerFichaPagoActionPerformed
      if(txtApellidosPa.getText().equals("") || Integer.parseInt(txtMeses.getText())==0)
                   
      {
          JOptionPane.showMessageDialog(this,"Debes de buscar un tratamiento del paciente que tenga cuotas","ADVERTENCIA",JOptionPane.WARNING_MESSAGE);
      }
              else
              {
       DialogFichaPagos.IDTRATAMIENTO = Integer.parseInt(txtIdTratamiento.getText());
       DialogFichaPagos dialogFichaPagos = new DialogFichaPagos(null, closable);
       dialogFichaPagos.setLocationRelativeTo(null);
       dialogFichaPagos.show();
              }
    }//GEN-LAST:event_btnVerFichaPagoActionPerformed

    private void btnVerControlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerControlesActionPerformed
                 if(txtApellidosPa.getText().equals(""))
      {
          JOptionPane.showMessageDialog(this,"Debes de buscar un tratamiento del paciente","ADVERTENCIA",JOptionPane.WARNING_MESSAGE);
      }
              else
              {
       DialogInfoControles.IDTRATAMIENTO = Integer.parseInt(txtIdTratamiento.getText());
       DialogInfoControles dialogInfoControlesl = new DialogInfoControles(null, closable);
       dialogInfoControlesl.setLocationRelativeTo(null);
       dialogInfoControlesl.show();
              }
    }//GEN-LAST:event_btnVerControlesActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
       PagoDAO pagoDAO = new PagoDAO();
        if(txtApellidosPa.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Debes de seleccionar un tratamiento del paciente","ADVERTENCIA",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
        List<Pago> pagos = new ArrayList<>();
        pagos = pagoDAO.listarPagosPorTratamiento(Integer.parseInt(txtIdTratamiento.getText()));
        List<PagosPacienteDTO> pagosPacienteDTOs = new ArrayList<>();

        double total = 0;
        double saldo = 0;
        double montoPagar = Double.parseDouble(txtCostoTotal.getText());

        for(Pago p:pagos)
        {
            PagosPacienteDTO pa = new PagosPacienteDTO();
            SimpleDateFormat sd = new SimpleDateFormat("dd 'de' MMMM 'de' yyyy", new Locale("ES"));
            String fecha = sd.format(p.getFechaPago());
            pa.setFechaPago(fecha);
            pa.setMontoTotal(String.valueOf(p.getMonto()));
            pa.setComentarios(p.getComentarios());
            total = total + p.getMonto();
            pagosPacienteDTOs.add(pa);

        }

        saldo = montoPagar - total;

        Map p = new HashMap();
        p.put("apellidos", txtApellidosPa.getText());
        p.put("nombres", txtNombresPa.getText());
         p.put("totalTratamiento", String.valueOf(txtCostoTotal.getText()));
        p.put("nroHistoria", txtNroHistoria.getText());
        p.put("total",String.valueOf(total));
        p.put("saldo",String.valueOf(saldo));

        String logo = "/imagenes/diamante.png";
        p.put("logo", this.getClass().getResourceAsStream(logo));
        JasperReport report;
        JasperPrint print;

        try {

            URL url = this.getClass().getResource("/reportes/RptPagosPaciente.jasper");
            report = (JasperReport) JRLoader.loadObject(url);
            //report = JasperCompileManager.compileReport(new File("").getAbsolutePath()+"\\src\\reportes\\RptContratoTratamiento.jrxml");
            print = JasperFillManager.fillReport(report, p, new JRBeanCollectionDataSource(pagosPacienteDTOs));
            JasperViewer view = new JasperViewer(print, false);
            //jasperviewer como dialog
            view.setTitle("PAGOS DEL PACIENTE");
            view.setVisible(true);

        } catch (JRException e) {
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_btnReporteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPorFecha;
    private javax.swing.JButton btnDetalleTratamiento;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JButton btnVerControles;
    private javax.swing.JButton btnVerFichaPago;
    private javax.swing.JButton btnVerPagos;
    private com.toedter.calendar.JMonthChooser cboMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JYearChooser spnAnho;
    private javax.swing.JTable tablePagosTratamiento;
    public static javax.swing.JTextField txtApellidosPa;
    public static javax.swing.JTextField txtCostoTotal;
    public static javax.swing.JTextField txtDiaPago;
    public static javax.swing.JTextField txtFechaRegistro;
    public static javax.swing.JTextField txtIdTratamiento;
    public static javax.swing.JTextField txtMeses;
    public static javax.swing.JTextField txtNombresPa;
    public static javax.swing.JTextField txtNroHistoria;
    public static javax.swing.JTextField txtPagoMensual;
    private javax.swing.JTextField txtSaldoPendiente;
    private javax.swing.JTextField txtTotalPagado;
    // End of variables declaration//GEN-END:variables
}
