/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.zealep.vista;

import com.zealep.backup.FrmRespaldarDB;
import com.zealep.backup.FrmRestaurarDB;
import com.zealep.util.ImagenFondo;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.UIManager;

/**
 *
 * @author CRISTHIAN
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        
        setUndecorated(true);
        //getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        initComponents();
        Escritorio.setBorder(new ImagenFondo());
        this.setExtendedState(MAXIMIZED_BOTH);
        lblId.setVisible(false);
           
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuArchivo = new javax.swing.JMenu();
        jMenuItemCerrarSesion = new javax.swing.JMenuItem();
        jMenuItemSalir = new javax.swing.JMenuItem();
        MenuPaciente = new javax.swing.JMenu();
        jMenuItemRegistrarPaciente = new javax.swing.JMenuItem();
        jMenuItemBuscarPaciente = new javax.swing.JMenuItem();
        jMenuItemCumpleaños = new javax.swing.JMenuItem();
        MenuTratamiento = new javax.swing.JMenu();
        jMenuItemRegistrarTratamiento = new javax.swing.JMenuItem();
        jMenuItemConsultarTratamiento = new javax.swing.JMenuItem();
        jMenuItemModificarTratamiento = new javax.swing.JMenuItem();
        jMenuItemProcedimientos = new javax.swing.JMenuItem();
        MenuControl = new javax.swing.JMenu();
        jMenuItemControles = new javax.swing.JMenuItem();
        MenuPagos = new javax.swing.JMenu();
        jMenuItemRegistrarPago = new javax.swing.JMenuItem();
        jMenuItemHistorialPagos = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        MenuDoctor = new javax.swing.JMenu();
        jMenuItemRegistrarDoctor = new javax.swing.JMenuItem();
        MenuCitas = new javax.swing.JMenu();
        jMenuItemRegistrarCita = new javax.swing.JMenuItem();
        MenuExamenes = new javax.swing.JMenu();
        jMenuItemRegistrarExamen = new javax.swing.JMenuItem();
        jMenuItemModificarExamen = new javax.swing.JMenuItem();
        jMenuItemBuscarExamen = new javax.swing.JMenuItem();
        MenuFinanzas = new javax.swing.JMenu();
        jMenuItemEgresos = new javax.swing.JMenuItem();
        jMenuItemFinanzas = new javax.swing.JMenuItem();
        MenuHerramientas = new javax.swing.JMenu();
        jMenuItemCambiarClave = new javax.swing.JMenuItem();
        jMenuItemCalculadora = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("USUARIO:");

        lblApellidos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblApellidos.setText("jLabel2");

        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombre.setText("jLabel4");

        lblId.setText("jLabel2");

        MenuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/archivo.png"))); // NOI18N
        MenuArchivo.setText("Archivo");

        jMenuItemCerrarSesion.setText("Cerrar Sesión");
        jMenuItemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCerrarSesionActionPerformed(evt);
            }
        });
        MenuArchivo.add(jMenuItemCerrarSesion);

        jMenuItemSalir.setText("Salir ");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        MenuArchivo.add(jMenuItemSalir);

        jMenuBar1.add(MenuArchivo);

        MenuPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/User2.png"))); // NOI18N
        MenuPaciente.setText("Paciente");

        jMenuItemRegistrarPaciente.setText("Gestión Paciente");
        jMenuItemRegistrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarPacienteActionPerformed(evt);
            }
        });
        MenuPaciente.add(jMenuItemRegistrarPaciente);

        jMenuItemBuscarPaciente.setText("Buscar Paciente");
        jMenuItemBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBuscarPacienteActionPerformed(evt);
            }
        });
        MenuPaciente.add(jMenuItemBuscarPaciente);

        jMenuItemCumpleaños.setText("Cumpleaños");
        jMenuItemCumpleaños.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCumpleañosActionPerformed(evt);
            }
        });
        MenuPaciente.add(jMenuItemCumpleaños);

        jMenuBar1.add(MenuPaciente);

        MenuTratamiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Ver_recibo.png"))); // NOI18N
        MenuTratamiento.setText("Tratamiento");

        jMenuItemRegistrarTratamiento.setText("Registrar Tratamiento");
        jMenuItemRegistrarTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarTratamientoActionPerformed(evt);
            }
        });
        MenuTratamiento.add(jMenuItemRegistrarTratamiento);

        jMenuItemConsultarTratamiento.setText("Consultar Tratamientos");
        jMenuItemConsultarTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarTratamientoActionPerformed(evt);
            }
        });
        MenuTratamiento.add(jMenuItemConsultarTratamiento);

        jMenuItemModificarTratamiento.setText("Modificar Tratamiento");
        jMenuItemModificarTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModificarTratamientoActionPerformed(evt);
            }
        });
        MenuTratamiento.add(jMenuItemModificarTratamiento);

        jMenuItemProcedimientos.setText("Gestion Procedimiento");
        jMenuItemProcedimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProcedimientosActionPerformed(evt);
            }
        });
        MenuTratamiento.add(jMenuItemProcedimientos);

        jMenuBar1.add(MenuTratamiento);

        MenuControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/asistencia_m.png"))); // NOI18N
        MenuControl.setText("Atención y Control");

        jMenuItemControles.setText("Gestión de Controles");
        jMenuItemControles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemControlesActionPerformed(evt);
            }
        });
        MenuControl.add(jMenuItemControles);

        jMenuBar1.add(MenuControl);

        MenuPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/calcular_32.png"))); // NOI18N
        MenuPagos.setText("Pagos");

        jMenuItemRegistrarPago.setText("Gestión Pago");
        jMenuItemRegistrarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarPagoActionPerformed(evt);
            }
        });
        MenuPagos.add(jMenuItemRegistrarPago);

        jMenuItemHistorialPagos.setText("Historial Pagos y Controles");
        jMenuItemHistorialPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHistorialPagosActionPerformed(evt);
            }
        });
        MenuPagos.add(jMenuItemHistorialPagos);

        jMenuItem1.setText("Pagos Pendientes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuPagos.add(jMenuItem1);

        jMenuBar1.add(MenuPagos);

        MenuDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/doctor.png"))); // NOI18N
        MenuDoctor.setText("Doctor");

        jMenuItemRegistrarDoctor.setText("Gestión Doctor");
        jMenuItemRegistrarDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarDoctorActionPerformed(evt);
            }
        });
        MenuDoctor.add(jMenuItemRegistrarDoctor);

        jMenuBar1.add(MenuDoctor);

        MenuCitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/folder.png"))); // NOI18N
        MenuCitas.setText("Cita");

        jMenuItemRegistrarCita.setText("Gestión Cita");
        jMenuItemRegistrarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarCitaActionPerformed(evt);
            }
        });
        MenuCitas.add(jMenuItemRegistrarCita);

        jMenuBar1.add(MenuCitas);

        MenuExamenes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ventasrealizadas.png"))); // NOI18N
        MenuExamenes.setText("Examen");

        jMenuItemRegistrarExamen.setText("Registro Examen");
        jMenuItemRegistrarExamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarExamenActionPerformed(evt);
            }
        });
        MenuExamenes.add(jMenuItemRegistrarExamen);

        jMenuItemModificarExamen.setText("Modificación Examen");
        jMenuItemModificarExamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModificarExamenActionPerformed(evt);
            }
        });
        MenuExamenes.add(jMenuItemModificarExamen);

        jMenuItemBuscarExamen.setText("Busqueda Examenes");
        jMenuItemBuscarExamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBuscarExamenActionPerformed(evt);
            }
        });
        MenuExamenes.add(jMenuItemBuscarExamen);

        jMenuBar1.add(MenuExamenes);

        MenuFinanzas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/comprasdetalladas.png"))); // NOI18N
        MenuFinanzas.setText("Finanzas");

        jMenuItemEgresos.setText("Gestión de Egresos");
        jMenuItemEgresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEgresosActionPerformed(evt);
            }
        });
        MenuFinanzas.add(jMenuItemEgresos);

        jMenuItemFinanzas.setText("Control Financiero");
        jMenuItemFinanzas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFinanzasActionPerformed(evt);
            }
        });
        MenuFinanzas.add(jMenuItemFinanzas);

        jMenuBar1.add(MenuFinanzas);

        MenuHerramientas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cog.png"))); // NOI18N
        MenuHerramientas.setText("Configuracion");

        jMenuItemCambiarClave.setText("Cambiar Contraseña");
        jMenuItemCambiarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCambiarClaveActionPerformed(evt);
            }
        });
        MenuHerramientas.add(jMenuItemCambiarClave);

        jMenuItemCalculadora.setText("Calculadora");
        jMenuItemCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCalculadoraActionPerformed(evt);
            }
        });
        MenuHerramientas.add(jMenuItemCalculadora);

        jMenuItem3.setText("Backup");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        MenuHerramientas.add(jMenuItem3);

        jMenuBar1.add(MenuHerramientas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblApellidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombre)
                .addGap(437, 437, 437)
                .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addComponent(lblId)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(lblApellidos)
                        .addComponent(lblNombre))
                    .addComponent(lblId)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItemRegistrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarPacienteActionPerformed
        FrmPaciente paciente = new FrmPaciente();
        Escritorio.add(paciente);
        paciente.show();
    }//GEN-LAST:event_jMenuItemRegistrarPacienteActionPerformed

    private void jMenuItemRegistrarTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarTratamientoActionPerformed
      FrmTratamiento tratamiento = new FrmTratamiento();
        Escritorio.add(tratamiento);
        tratamiento.show();
    }//GEN-LAST:event_jMenuItemRegistrarTratamientoActionPerformed

    private void jMenuItemProcedimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProcedimientosActionPerformed
       FrmProcedimiento tipoTratamiento = new FrmProcedimiento();
        Escritorio.add(tipoTratamiento);
        tipoTratamiento.show();
    }//GEN-LAST:event_jMenuItemProcedimientosActionPerformed

    private void jMenuItemCambiarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCambiarClaveActionPerformed
        FrmCambiarClave cambiarClave = new FrmCambiarClave();
        Escritorio.add(cambiarClave);
        cambiarClave.show();
    }//GEN-LAST:event_jMenuItemCambiarClaveActionPerformed

    private void jMenuItemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCerrarSesionActionPerformed
         this.dispose();
        com.zealep.vista.FrmLogin Login=new com.zealep.vista.FrmLogin();

        Login.show();

    }//GEN-LAST:event_jMenuItemCerrarSesionActionPerformed

    private void jMenuItemRegistrarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarPagoActionPerformed
        FrmPago pago = new FrmPago();
        Escritorio.add(pago);
        pago.show();
    }//GEN-LAST:event_jMenuItemRegistrarPagoActionPerformed

    private void jMenuItemHistorialPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHistorialPagosActionPerformed
        FrmHistorialPago historialPago = new FrmHistorialPago();
        Escritorio.add(historialPago);
        historialPago.show();
    }//GEN-LAST:event_jMenuItemHistorialPagosActionPerformed

    private void jMenuItemCumpleañosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCumpleañosActionPerformed
        FrmCumpleaños cumpleaños  = new FrmCumpleaños();
        Escritorio.add(cumpleaños);
        cumpleaños.show();
    }//GEN-LAST:event_jMenuItemCumpleañosActionPerformed

    private void jMenuItemRegistrarDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarDoctorActionPerformed
        FrmDoctor doctor = new FrmDoctor();
        Escritorio.add(doctor);
        doctor.show();
    }//GEN-LAST:event_jMenuItemRegistrarDoctorActionPerformed

    private void jMenuItemRegistrarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarCitaActionPerformed
        FrmCita cita = new FrmCita();
        Escritorio.add(cita);
        cita.show();
    }//GEN-LAST:event_jMenuItemRegistrarCitaActionPerformed

    private void jMenuItemCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCalculadoraActionPerformed
         try
        {
            Runtime obj = Runtime.getRuntime();
            obj.exec("C:\\WINDOWS\\system32\\CALC.EXE");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } 
    }//GEN-LAST:event_jMenuItemCalculadoraActionPerformed

    private void jMenuItemRegistrarExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarExamenActionPerformed
       FrmExamen frmExamen = new FrmExamen();
       Escritorio.add(frmExamen);
       frmExamen.show();
    }//GEN-LAST:event_jMenuItemRegistrarExamenActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        FrmRespaldarDB frmRespaldarDB = new FrmRespaldarDB();
        Escritorio.add(frmRespaldarDB);
        frmRespaldarDB.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItemConsultarTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarTratamientoActionPerformed
        FrmConsultaTratamiento frmConsultaTratamiento = new FrmConsultaTratamiento();
        Escritorio.add(frmConsultaTratamiento);
        frmConsultaTratamiento.show();
    }//GEN-LAST:event_jMenuItemConsultarTratamientoActionPerformed

    private void jMenuItemBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBuscarPacienteActionPerformed
        FrmBuscarPaciente frmBuscarPaciente = new FrmBuscarPaciente();
        Escritorio.add(frmBuscarPaciente);
        frmBuscarPaciente.show();
    }//GEN-LAST:event_jMenuItemBuscarPacienteActionPerformed

    private void jMenuItemModificarTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModificarTratamientoActionPerformed
        FrmModificarTratamiento frmModificarTratamiento = new FrmModificarTratamiento();
        Escritorio.add(frmModificarTratamiento);
        frmModificarTratamiento.show();
    }//GEN-LAST:event_jMenuItemModificarTratamientoActionPerformed

    private void jMenuItemControlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemControlesActionPerformed
        FrmControl frmControl = new FrmControl();
        Escritorio.add(frmControl);
        frmControl.show();
    }//GEN-LAST:event_jMenuItemControlesActionPerformed

    private void jMenuItemModificarExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModificarExamenActionPerformed
        FrmModificarExamenes frmModificarExamenes = new FrmModificarExamenes();
        Escritorio.add(frmModificarExamenes);
        frmModificarExamenes.show();
    }//GEN-LAST:event_jMenuItemModificarExamenActionPerformed

    private void jMenuItemBuscarExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBuscarExamenActionPerformed
        FrmBuscarExamenes frmBuscarExamenes = new FrmBuscarExamenes();
        Escritorio.add(frmBuscarExamenes);
        frmBuscarExamenes.show();
    }//GEN-LAST:event_jMenuItemBuscarExamenActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmPagosPendientes frmPagosPendientes = new FrmPagosPendientes();
        Escritorio.add(frmPagosPendientes);
        frmPagosPendientes.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemEgresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEgresosActionPerformed
        FrmEgreso frmEgreso = new FrmEgreso();
        Escritorio.add(frmEgreso);
        frmEgreso.show();
    }//GEN-LAST:event_jMenuItemEgresosActionPerformed

    private void jMenuItemFinanzasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFinanzasActionPerformed
        FrmFinanzas frmFinanzas = new FrmFinanzas();
        Escritorio.add(frmFinanzas);
        frmFinanzas.show();
    }//GEN-LAST:event_jMenuItemFinanzasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         try {
         
          //UIManager.setLookAndFeel("de.javasoft.plaf.synthetica.SyntheticaBlueLightLookAndFeel");
               UIManager.setLookAndFeel("de.javasoft.plaf.synthetica.SyntheticaSkyMetallicLookAndFeel");
        } catch (Exception e) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane Escritorio;
    public static javax.swing.JMenu MenuArchivo;
    private javax.swing.JMenu MenuCitas;
    private javax.swing.JMenu MenuControl;
    private javax.swing.JMenu MenuDoctor;
    private javax.swing.JMenu MenuExamenes;
    private javax.swing.JMenu MenuFinanzas;
    public static javax.swing.JMenu MenuHerramientas;
    public static javax.swing.JMenu MenuPaciente;
    public static javax.swing.JMenu MenuPagos;
    public static javax.swing.JMenu MenuTratamiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemBuscarExamen;
    private javax.swing.JMenuItem jMenuItemBuscarPaciente;
    private javax.swing.JMenuItem jMenuItemCalculadora;
    private javax.swing.JMenuItem jMenuItemCambiarClave;
    private javax.swing.JMenuItem jMenuItemCerrarSesion;
    private javax.swing.JMenuItem jMenuItemConsultarTratamiento;
    private javax.swing.JMenuItem jMenuItemControles;
    private javax.swing.JMenuItem jMenuItemCumpleaños;
    private javax.swing.JMenuItem jMenuItemEgresos;
    private javax.swing.JMenuItem jMenuItemFinanzas;
    private javax.swing.JMenuItem jMenuItemHistorialPagos;
    private javax.swing.JMenuItem jMenuItemModificarExamen;
    private javax.swing.JMenuItem jMenuItemModificarTratamiento;
    private javax.swing.JMenuItem jMenuItemProcedimientos;
    private javax.swing.JMenuItem jMenuItemRegistrarCita;
    private javax.swing.JMenuItem jMenuItemRegistrarDoctor;
    private javax.swing.JMenuItem jMenuItemRegistrarExamen;
    private javax.swing.JMenuItem jMenuItemRegistrarPaciente;
    private javax.swing.JMenuItem jMenuItemRegistrarPago;
    private javax.swing.JMenuItem jMenuItemRegistrarTratamiento;
    private javax.swing.JMenuItem jMenuItemSalir;
    public static javax.swing.JLabel lblApellidos;
    public static javax.swing.JLabel lblEstado;
    public static javax.swing.JLabel lblId;
    public static javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables

}
